name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # PyStan (stan) needs Cython & numpy at build time
      - name: Install build-time tools
        run: pip install Cython numpy

      - name: Install runtime dependencies
        run: |
         pip install pandas matplotlib pystan nest_asyncio pytest cmdstanpy

      - name: Install CmdStan binaries
        run: python -m cmdstanpy.install_cmdstan

      # Install your package in editable mode so `import o2o` works
      - name: Install package itself
        run: pip install -e .

      - name: Run test suite
        run: pytest -q

