name: Run Tests

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Fetch your code
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # 3. Pre-install build-time deps (needed on macOS for PyStan)
      - name: Install build-time dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy cython

      # 4. Install runtime dependencies
      - name: Install runtime dependencies
        run: |
          pip install pandas matplotlib pystan nest_asyncio pytest

      # 5. Add your package root to PYTHONPATH so "import" o2o works
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):\$PYTHONPATH" >> $GITHUB_ENV

      # 6. Run your tests
      - name: Run pytest
        run: pytest -q

