name: Run Tests

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Upgrade pip & install build-tools
        run: |
          python -m pip install --upgrade pip
          pip install Cython numpy

      - name: Install runtime deps and package
        run: |
          pip install pandas matplotlib pystan nest_asyncio pytest
          pip install -e .

      - name: Run tests
        run: pytest

